Feature/3.0.x new
kahvedigital/iyzico-opencart pull request #18
Opened 2017-07-27 21:24 UTC by kahvedigital

Opencart 3.0.x Yeni Sürüm

2017-08-08 11:49 UTC, heheok requested changes

2017-08-08 11:49 UTC, heheok commented on admin/controller/extension/payment/iyzico_checkout_form.php
> +error_reporting(E_ALL);
bu error reporting'in kapalı olması gerekiyor. server ile ilgili hassas bilgileri ekrana basma riski var.

2017-08-08 11:49 UTC, heheok commented on admin/language/tr-tr/extension/payment/iyzico_checkout_form.php
> +$_['entry_order_status'] = 'Satın sonrası al Durum';
Bu çeviriler yanlış.  Tekrar elden geçirilmesi lazım. "Satın sonrası al durum" ne demek?

Çeviriyi google ile yapıyorsanız da sonrasında cümle ne anlama gelmeli, okuyunca ne anlıyorum diye bakmak lazım. Hepsine tek tek yorum yapmayacağım, zaten dosyayı baştan aşağı tarayınca problemli çevirilerin hepsi belli.

2017-08-08 11:49 UTC, heheok commented on catalog/controller/extension/payment/iyzico_checkout_form.php
> +error_reporting(1);
error reporting'i development time'da debugging hariç kullanMAMAK gerekiyor.

2017-08-08 11:49 UTC, heheok commented on catalog/language/en-gb/extension/payment/iyzico_checkout_form.php
> +$_['text_issue'] = '(for Maestro and Solo cards only)';
SOLO card nedir?

2017-08-08 11:49 UTC, heheok commented on catalog/language/en-gb/extension/payment/iyzico_checkout_form.php
> +$_['Error_message_curl'] = 'You have to enable PHP CURL Extention on this server';
Bu son kullanıcının göreceği ekranda gösterilecek ise server'la ilgili detay son kullanıcıyı ilgilendirmediğinden hata mesajını değiştirmek gerekiyor.

2017-08-08 11:49 UTC, heheok commented on catalog/language/tr-tr/extension/payment/iyzico_checkout_form.php
> +$_['Error_message_curl'] = 'Sunucunuzda PHP CURL eklentisini etkinleştirmeniz gerekir';
Bu son kullanıcının göreceği ekranda gösterilecek ise server'la ilgili detay son kullanıcıyı ilgilendirmediğinden hata mesajını değiştirmek gerekiyor.

2017-08-10 21:50 UTC, kahvedigital commented
Değişiklikler güncellendi

2017-08-15 12:59 UTC, heheok requested changes
Çevirilere daha fazla dikkat etmek gerekiyor... Aynı zamanda conflict var, README.md dosyası conflict veriyor, onun da düzeltilmesi lazım.

2017-08-15 12:59 UTC, heheok commented on admin/language/tr-tr/extension/payment/iyzico_checkout_form.php
> +$_['heading_title'] = 'Iyzico Ödeme Formu';
I küçük, her zaman...

2017-08-15 12:59 UTC, heheok commented on admin/language/tr-tr/extension/payment/iyzico_checkout_form.php
> +$_['text_link'] = 'iyzico pazar yeri sistemine kayıt olmak için';
"İyzico Üye İşyeri olmak için kayıt olun."

2017-08-15 12:59 UTC, heheok commented on admin/language/tr-tr/extension/payment/iyzico_checkout_form.php
> +$_['entry_api_id_live'] = 'Live Api Id';
"Canlı API ID"

2017-08-15 12:59 UTC, heheok commented on admin/language/tr-tr/extension/payment/iyzico_checkout_form.php
> +$_['entry_secret_key_live'] = 'Live Secret Key';
Canlı Secret Key

2017-08-15 12:59 UTC, heheok commented on admin/language/tr-tr/extension/payment/iyzico_checkout_form.php
> +$_['entry_error_version_updated'] = 'Güncelleme Hatası! güncellemek için iyzico entegrasyon sayfasına giderek indirebilirsiniz. <a href="https://www.iyzico.com/entegrasyon/hazir-altyapi/opencart/" ta
"Güncelleme Hatası! Manuel olarak güncellemek için <a href="https://www.iyzico.com/entegrasyon/hazir-altyapi/opencart/" target="_blank">tıklayın</a>."

2017-08-15 12:59 UTC, heheok commented on admin/language/tr-tr/extension/payment/iyzico_checkout_form.php
> +$_['error_secret_key_live'] = 'Gizli anahtarı gereklidir!';
"Secret Key Gereklidir"

2017-08-15 12:59 UTC, heheok commented on admin/language/tr-tr/extension/payment/iyzico_checkout_form.php
> +$_['iyzico_single_keys_must_configured'] = "Bu eklenti üzerinde değişiklik yapabilmeniz için eklendinin kurulu olması gereklidir";
"eklendinin" değil, "eklentinin"

2017-08-15 12:59 UTC, heheok commented on admin/language/tr-tr/extension/payment/iyzico_checkout_form.php
> +$_['Invalid call.'] = 'Geçersiz arayın.';
"Geçersiz İstek"

2017-08-15 12:59 UTC, heheok commented on admin/language/tr-tr/extension/payment/iyzico_checkout_form.php
> +$_['payment_transaction_type'] = 'Ödeme İşlemi';
"Ödeme işlem tipi"

2017-08-15 12:59 UTC, heheok commented on admin/language/tr-tr/extension/payment/iyzico_checkout_form.php
> +$_['text_action'] = 'Aksiyon';
"İşlem"

2017-08-15 12:59 UTC, heheok commented on admin/language/tr-tr/extension/payment/iyzico_checkout_form.php
> +$_['text_are_you_sure'] = 'Bu işlemi yapmak için devam etmek istiyormusunuz?';
"Bu işlemi gerçekleştirmek istediğinizden emin misiniz?"

2017-08-15 12:59 UTC, heheok commented on admin/language/en-gb/extension/payment/iyzico_checkout_form.php
> +$_['heading_title'] = 'Iyzico Checkout Form';
"I" her zaman küçük

2017-08-15 12:59 UTC, heheok commented on admin/language/en-gb/extension/payment/iyzico_checkout_form.php
> +$_['entry_error_version_updated'] = 'Update Error! go to iyzico version page <a href="https://www.iyzico.com/entegrasyon/hazir-altyapi/opencart/" target="_blank">Version page</a> ';
"Update Error! <a href="https://www.iyzico.com/entegrasyon/hazir-altyapi/opencart/" target="_blank">Click here </a> to manually update the plugin.

2017-08-15 12:59 UTC, heheok commented on admin/language/en-gb/extension/payment/iyzico_checkout_form.php
> +$_['refund_done_success'] = 'Refund done successfully. Item Id: %s, Item Name: %s, Amount: %s';
"Payment successfully refunded. Item Id: %s, Item Name: %s, Amount: %s"

2017-08-21 01:34 UTC, kahvedigital commented
Değişiklikler yapıldı

2017-08-21 08:53 UTC, merged