Feature/2.3.x kart saklama
kahvedigital/iyzico-opencart pull request #6
Opened 2016-10-08 00:16 UTC by kahvedigital

2.3.x için kart saklama auto update ve 2.3 versiyonuna uyumluluk sorunları çeşitli bug fixleri test ok

2016-10-10 07:16 UTC, heheok requested changes
Bu ufak sorunları giderirsek merge edeceğim.

2016-10-10 07:16 UTC, heheok commented on admin/controller/extension/payment/iyzico_checkout_form.php
> +        error_reporting(0);
Bu error reporting kapatma işini PHP dosyasının başında bir kereye mahsus yapmak daha mantıklı, birden fazla method içinde gereksiz yere kod tekrarı oluşuyor.

Todo: error_reporting(0) satırını her yerden kaldırıp sadece <?php ile açtığımız dosya başına koymamız lazım.

2016-10-10 07:16 UTC, heheok commented on admin/controller/extension/payment/iyzico_checkout_form.php
> +        error_reporting(0);
Bu error_reporting'e de gerek kalmayacak dosya başına koyarsak satırı.

2016-10-10 07:16 UTC, heheok commented on admin/controller/extension/payment/iyzico_checkout_form.php
> +        error_reporting(0);
yine error_reporting.

2016-10-10 07:16 UTC, heheok commented on admin/controller/extension/payment/iyzico_checkout_form.php
> +        error_reporting(0);
error_reporting kalkacak.

2016-10-10 07:16 UTC, heheok commented on catalog/controller/extension/payment/iyzico_checkout_form.php
>                  error_reporting(0);
Bu error reporting kapatma işini PHP dosyasının başında bir kereye mahsus yapmak daha mantıklı, birden fazla method içinde gereksiz yere kod tekrarı oluşuyor.

Todo: error_reporting(0) satırını her yerden kaldırıp sadece <?php ile açtığımız dosya başına koymamız lazım.

2016-10-10 07:16 UTC, heheok commented on catalog/controller/extension/payment/iyzico_checkout_form.php
>          error_reporting(0);
error_reporting tek yerde olmalı.

2016-10-10 07:16 UTC, heheok commented on admin/controller/extension/payment/iyzico_checkout_form.php
> +
Gereksiz boşluk. kaldıralım

2016-10-10 07:16 UTC, heheok commented on admin/controller/extension/payment/iyzico_checkout_form.php
> +
gereksiz boşluk, kaldıralım.

2016-10-10 07:16 UTC, heheok commented on admin/controller/extension/payment/iyzico_checkout_form.php
> +
gereksiz boşluk.

2016-10-10 07:16 UTC, heheok commented on admin/controller/extension/payment/iyzico_checkout_form.php
> +
gereksiz boşluk.

2016-10-10 07:16 UTC, heheok commented on admin/controller/extension/payment/iyzico_checkout_form.php
> +
gereksiz boşluk.

2016-10-10 07:16 UTC, heheok commented on admin/controller/extension/payment/iyzico_checkout_form.php
> +
her satıra tek tek yazmıyoruzi bundan sonraki tüm diğer gereksiz boşlukları kaldıralım

2016-10-10 07:16 UTC, heheok commented on admin/model/extension/payment/iyzico_checkout_form.php
> +        mkdir($fullfoldername);
bu isimde dosya zaten var ise ne olacak? Burada varsa silmek sonra tekrar mkdir yapmak daha iyi olabilir.

2016-10-10 07:16 UTC, heheok commented on catalog/controller/extension/payment/iyzico_checkout_form.php
>                  error_reporting(0);
bu satır da gereksiz.

2016-10-10 07:16 UTC, heheok commented on catalog/controller/extension/payment/iyzico_checkout_form.php
>                  error_reporting(0);
bu da gereksiz.

2016-10-11 14:16 UTC, kahvedigital commented
dosylar eklendi

2016-10-13 11:58 UTC, merged